language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: test
      script:
        - npm install gulp -g
        - gulp test
    - stage: release
      script:
        - npm install gulp -g
        - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_COMMIT_MESSAGE != Release* ]]; then bash ./travis-prepare-git.sh && gulp release-ci --browser=chrome --release=minor; fi;
    - stage: publish
      script:
        - npm install gulp -g
        - if [[ $TRAVIS_TAG ]]; then gulp publish-ci --browser=chrome --production; fi;
